<div class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
  <div>
    <label>CPF/CNPJ</label>
    <span>
      <input type="text" title="<?php echo $this->__('Custom Field One') ?>" name="payment[cpf_cnpj_paghiper]" value="<?php echo $this->htmlEscape($this->cpf_cnpj) ?>" />
    </span>
  </div>
</div>
<div>
    <?php echo $this->getMethod()->getConfigData('message');?>
</div>