<p><?php echo $this->getMethod()->getTitle(); ?></p><br>

<?php
if($this->getInfo()->getOrder() && $this->getInfo()->getOrder()->getState() != 'canceled'){
    if($this->getInfo()->hasAdditionalInformation('vencimento')){
        echo '<p>Vencimento: '. date('d/m/Y', strtotime($this->getInfo()->getAdditionalInformation('vencimento'))) .'</p>';
    }
    if($this->getInfo()->hasAdditionalInformation('linha_digitavel')){
    ?>
        <p>
            <p>Linha digitável:</p>
            <input type="text" value="<?php echo $this->getInfo()->getAdditionalInformation('linha_digitavel');?>" id="linha_digitavel" style="float: left; width: 80%; padding: 10px; box-sizing: border-box;" readonly /> <button type="button" style="float: left; width: 20%; padding: 3px; box-sizing: border-box; margin-top: 2px;" onclick="copyLinha();">Copiar</button>
            <script>
            function copyLinha() {
            var copyText = document.getElementById("linha_digitavel");
            copyText.select();
            document.execCommand("copy");
            }
            </script>
        </p><br><br><br>
    <?php
    }
    if($this->getInfo()->hasAdditionalInformation('boleto_url')){
        echo '<button type="button" class="scalable go" onclick="window.open(\''. $this->getInfo()->getAdditionalInformation('boleto_url') .'\', \'_blank\')">Imprimir boleto</button>';
    }else{
        $url = Mage::helper('adminhtml')->getUrl('paghiper/boleto/generate', ['order_id' => $this->getInfo()->getOrder()->getIncrementId()]);
        echo '<p style="float: left; width: 100%; padding: 10px; color: #FFF; background: #C00; box-sizing: border-box;">Boleto não gerado! <a href="'. $url .'" style="color: #FFF; text-decoration: underline;">Gerar boleto</a></p>';
    }
    echo '<br><br>';
}
?>
